name: Create terraform plan on folder

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clone role ansible
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        repository: 'caiosampaio894/vagrant-ansible-docker'
        path: ./ansible/roles/vagrant-ansible-docker
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Build AMI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        sudo apt-get install -y packer ansible
        sudo packer build  -var "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} -var "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}" ./packer/build.json